### ISSUE TITLE
About the Hydra launcher and its problems

### ISSUE THREAD

**Issue by Lemon4ik-bit** [hydralauncher/hydra#1079]
In this post, I want to talk about some of the shortcomings of Hydra launcher. The launcher itself is good.
Here are the disadvantages I've encountered:
1. After downloading all files from ‘Hydra community links’ (https://hydralinks.cloud) I encountered that not all games are available in Hydra launcher.

2. Some repacks do not match the games.
Read more: I wanted to download the game ‘Stray’ (it's a cat game)
When I downloaded the repack I thought the title was strange. And yes it was a completely different game with the name ‘Stray’ in it. But this is a completely different game!!!!! Having looked carefully I saw that this is not the only repack which does not correspond to the game.

3.The file ( I used torrent) loads slowly in the launcher. I still don't understand how it works. Yesterday the file almost didn't load (4-17kb). My internet connection is fine. Unexpectedly for me Hydra launcher today started loading files better. I don't know what it can be connected with.

4.I don't know if it's worth mentioning. For example ‘Wallpaper engine’ programme refuses to work (asks for ‘Steam’) Are there any other such programmes I don't know.

Below are screenshots of the problem numbers.

1.And there are many more games like this. (open screenshot)
(https://github.com/user-attachments/assets/5d95416f-592f-4657-b6a2-f4256fa6ec9b)

2.What's marked with crosses is not the game that should be.
(https://github.com/user-attachments/assets/f83bc823-39a8-4f5c-be5e-8d7f60d9c5f0)

3.There's no picture. But I don't think it's necessary. It's pretty self-explanatory.

4.In the application writes that ‘Configuration with “Steam” is not completed. Open Steam.’

**Comment by JackEnx** [comment]
Hello, thanks for the information.

1. adding a link only makes what is in it available, hydra has no relation to hydralinks.

2. Hydra tries to match the name provided in the json with the game name, which causes the wrong match of game A with B because they have similar names or parts of the name such as God of War and God of War: Ragnarok, both appear in God of War. the links are not native to Hydra and are supported by the community itself. if a game does not have a match, it appears as "no download available", all matching process is local and automatic, the problem is, the more restrictive the match, the greater the chance of a game not being indexed, where you simply receive any download (we have future plans for improvements, next update is part of the necessary for that).

3. regarding the download rate, Hydra uses the [bittorrent](https://en.wikipedia.org/wiki/BitTorrent) protocol, specifically an instance of [libtorrent](https://en.wikipedia.org/wiki/Libtorrent), the same one used by [qbittorrent](https://en.wikipedia.org/wiki/QBittorrent), or http download using RealDebrid (paid and requires a key), where you insert your key into Hydra and perform downloads through it and some hosts.

4. we do not support what is downloaded.

**Comment by Lemon4ik-bit** [comment]
Thanks

**Comment by Jasukann** [comment]
Точно такая же проблема(
+ не могу зайти в аккаунт, как я понял проблема с капчей. Иногда пропускает, но тк не могу загрузить источники загрузок - проблема не решается))))
Пишу в поддержку с того года, выходные, пока не решился вопрос
