### ISSUE TITLE
Game admin mode

### ISSUE THREAD

**Issue by xbozo** [hydralauncher/hydra#140]
Hydra launches as in admin mode and I think this is necessary for some reasons which i'm not entirely up to in order to comment.

The thing is, games executed through Hydra also gets launched on Admin mode. This is inconvenient in most cases because other applications don't have priority over it.

So for example Discord, when you launch a game as admin mode, discord loses priority and you can't talk through push to talk unless you reopen discord also on admin mode.

This is valid for other applications as well. Discord is the one I found the most inconvenient.

**Comment by thegrannychaseroperation** [comment]
Not all applications launched through an application with higher privileges will be launched as admin.
Only binaries that have been already flagged with the necessity to launch with UAC by the compiler will ask for it.
Closing this for now since it's not a Hydra's issue, but rather a Windows behaviour.
