### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by Kinger101** [hydralauncher/hydra#219]
**Hydra**, at least for me, is limiting the amount of MBS it uses, most of the time I see it with 14.50KBs to 31.60KBs. I ask that if it is an error that you fix it as quickly as possible. My Wi-Fi is a little bad, but it's not for **Hydra** to download a game at less than **1MB**.
![imagem_2024-05-06_192305403](https://github.com/hydralauncher/hydra/assets/169103654/4140afdf-99ef-4922-b00b-822065fd45a8)

**Comment by hydralauncher** [comment]
“fix it as quickly as possible”? Feel free to open a PR solving the issue of the torrents that you are downloading not being seeded, if you can. Please learn better how torrenting works.

**Comment by Spillernatt** [comment]
That's actually an interesting problem to bring up, since Hydra uses torrent, it should have a few download options such as torrent has, like limiting download speed and seeding, if we have no seeders we have no download with torrent
About your problem i suggest you check how many peers and seeds your downloading game has, the speed depends on that. 
When clicking downloads it shows right there under the percentage (see image)
![image](https://github.com/hydralauncher/hydra/assets/63877530/0685adbc-c0c7-437b-8e6e-9c78de78a9e7)
_**Hope it helps!!**_

**Comment by nykbocks** [comment]
yep,the downloads is taking too long,installing darksiders,less than a MB,so sad a awesome launcher is suffering of this,hope this is some internal problem that can get fixed.

**Comment by WADS000** [comment]
Увсех пишет 1 год?
