### ISSUE TITLE
PDM: Trojan.Win32.Generic

### ISSUE THREAD

**Issue by LMGarrido** [hydralauncher/hydra#472]
Hello guys, in my Kaspersky it gave this: "PDM:Trojan.Win32.Generic" and it didn't even let me do anything, it deleted it directly. Proceeds? (Edit: About Hydra)

**Comment by JackEnx** [comment]
Do whatever makes you feel safer. 

I don't know if you're talking about Hydra or a game, I'll explain it to both

About the trojan: "Generic" trojan is a file that makes unwanted system modifications, this does not necessarily mean malicious modifications (with the aim of harming the user), but that they are at least suspicious.

In games: Is common depending on how the game's protection was broken, especially DENUVO. 

In hydra: We had problems with false detection in Hydra itself, mainly in older versions due to python build or the fact hydra code don't have a windows software signature. I'm not sure what criteria these programs use to determine a "Trojan", but it is extremely common in programs without a windows signature.

**Comment by FarParticul** [comment]
Look, hydra is open source and there can't be any viruses on it. It must be a repack or the game itself.

**Comment by sterepandopalcevsto** [comment]
> Смотрите, гидра с открытым исходным кодом, и на ней не может быть никаких вирусов. Это должен быть репак или сама игра.

в опенсорс тоже бывают вирусы и насчёт обнаружений "многих гребут к вирусом тупо из-за отсутствия подписи windows и вот вопрос а пиратки эту подпись должы иметь? естественно нет, я буду больше доверять пиратке у которой не будет подписи, просто пиратка с подписью это уже звоночек (я больше скажу делал вирусную презентацию и вирус смог скрыть с помощью подписи)

**Comment by FarParticul** [comment]
> > Смотрите, гидра с открытым исходным кодом, и на ней не может быть никаких вирусов. Это должен быть репак или сама игра.
> 
> в опенсорс тоже бывают вирусы и насчёт обнаружений "многих гребут к вирусом тупо из-за отсутствия подписи windows и вот вопрос а пиратки эту подпись должы иметь? естественно нет, я буду больше доверять пиратке у которой не будет подписи, просто пиратка с подписью это уже звоночек (я больше скажу делал вирусную презентацию и вирус смог скрыть с помощью подписи)

Хорошо, я понял. Вроде помню что на гитхабе был вроде как вирус, но позабыл

**Comment by zamitto** [comment]
Closing as:

1) We request to keep issues in English
2) We are aware that some antiviruses recognize Hydra as a virus/trojan/etc, there is not much else we can do about it as we can't pay to sign our program
