### ISSUE TITLE
The launcher can't be installed anymore

### ISSUE THREAD

**Issue by Akieos** [hydralauncher/hydra#50]
After the 1.1.0 update my antivirus got a false positive with the installer and the launcher doesn't install nor open even with everything turned off security wise.

**Comment by Magrid0** [comment]
It works normally for me, I just downloaded it an hour ago

**Comment by hydralauncher** [comment]
If you cant open setup.exe you need restore the file from quarantine or allow on your av (like win defender)

If you can install but launcher close after open you can try to add `--no-sandbox` flag to Hydra shortcut

**Comment by victormga** [comment]
@hydralauncher commenting here because i don't think this deserves an open issue, this might be related with false positives. how feasible is to scrap the python dependency and use a node.js torrent client (eg: https://github.com/webtorrent/webtorrent), making this an exclusively electron application? i have some personal projects setup with electron and webtorrent and none is detected as as viruses.

**Comment by hydralauncher** [comment]
Very unlikely. WebTorrent is bloated with issues and things that you have to workaround in order to get it working, and does still get flagged (Hydra was written using it before). Plus, libtorrent has such a great performance + plenty of features that we can use. Being a separated process is not the reason with the executable gets flagged, but rather having a bittorrent client instead does.

**Comment by hydralauncher** [comment]
Solved by the migration to electron-builder.
