### ISSUE TITLE
[BUG] Downloads a wrong game

### ISSUE THREAD

**Issue by antoxa-kms** [hydralauncher/hydra#538]
### Describe the bug

When downloading some games, the launcher may download a completely different game than the one you selected.

### Steps to Reproduce

Examples are attached in the screenshots

### Expected behavior

To load what I choose

### Screenshots

![Снимок экрана 2024-05-29 132454](https://github.com/hydralauncher/hydra/assets/49340651/938cbff1-41f2-4d2d-a974-ef60b4a162e5)
![Снимок экрана 2024-05-29 132522](https://github.com/hydralauncher/hydra/assets/49340651/2ffc0f7d-6664-4714-addc-97bfd84e9377)
![Снимок экрана 2024-05-29 132543](https://github.com/hydralauncher/hydra/assets/49340651/03f85a98-5025-42e5-a28d-cee2b18249cf)

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by zamitto** [comment]
Since 2.0, Hydra has no responsability on the downloads available. 
You can wipe you hydra.db (located at "%appdata%/hydra") to clean everything that was added before, and add your own sources (you can find help on the community discord server).
Just make sure to create and account and synchronizing your library before deleting your local datase
