### ISSUE TITLE
Installing didn't happen, and now my laptop start to make noises and lagging

### ISSUE THREAD

**Issue by stillnotfamou** [hydralauncher/hydra#670]
### Describe the bug

How can i delete it? No files i can find except of .exe shortcut

### Steps to Reproduce

No steps, i installed setup

### Expected behavior

Obviusly not this

### Operating System

WIn 11

### Hydra Version

v2.0.1

**Comment by zamitto** [comment]
If you want to uninstall Hydra you can do it from windows apps list

Hydra files are located in "%appdata%/hydra", "%localappdata%/hydra" and "%localappdata%/hydralauncher"

**Comment by stillnotfamou** [comment]
Problem is that Hydra didn't even installed, there was error and laptop started lagging bruh

**Comment by Xxxsusx** [comment]
Then, if your computer starting lagging then that's your computer problem and not Hydra. I mean, how are you supposed to fix the "bug" it self if you can't give at least minimum information such as what was written on the error? Plus, it cannot be Hydra since it's a open source software meaning its source code is open public and contains no virus or any type of malware.

If I were you, at this point I would just do a fresh install of Windows (Make a backup of important files before that of course) or eventually go to advanced options, and try to restore the computer to a previous point.

**Comment by JackEnx** [comment]
Please, if you open an issue at least provide enough information about the problem, try install version 2.0.2, if you notice the same problem check your task manager and see if any installation process is active, anything comment again on this issue
