### ISSUE TITLE
[IDK] Download is too lasy

### ISSUE THREAD

**Issue by aumondj** [hydralauncher/hydra#673]
### Describe the bug

My download simply is too lasy, 10KB/s

### Steps to Reproduce

Try to download the game

### Expected behavior

Download normally

### Operating System

Windows 10

### Hydra Version

2.0.1

**Comment by GlebDubStep** [comment]
too

**Comment by Xxxsusx** [comment]
I'm not a developer, neither a contributor on Hydra, but I call tell you why that happens. You see, Hydra is not a software with cracked games/software from their server, all the files are from different servers that makes cracked/pirated files of those games. And those servers aren't associated with Hydra. They are public servers (most commonly from Russia or other countries) that make those files. And because of that, sometimes the download can be REALLY slow. It's not about your network speed, it also matters from what region or place that server is. 

What's the problem here exactly? The server on that region/country connecting to your computer. That happens a LOT when installing cracked games/software from websites and sadly there isn't pretty much what to do about it.

(Also, sorry to inform you that this isn't a bug and it's a completely normal thing when downloading software from those servers.)

**Comment by JackEnx** [comment]
please, check the 2.0.2 version, if the problem persist, report it
