### ISSUE TITLE
Trojan:Win32/Acll in the installation .exe

### ISSUE THREAD

**Issue by devcoar** [hydralauncher/hydra#70]
Windows Defender detects Trojan:Win32/Acll in the setup.exe. Any ideas why?

**Comment by hydralauncher** [comment]
Most likely due to low application score and lack of digital signature.

**Comment by zenflow** [comment]
> due to low application score and lack of digital signature

@hydralauncher I have no idea what you're talking about and frankly it sounds like nonsense excuse for a TROJAN being detected in thesetup.exe...

but if that's the issue then why don't you fix it?

**Comment by hydralauncher** [comment]
https://www.electronjs.org/docs/latest/tutorial/code-signing

If you're willing to lend me the 400€ for the digital license I can fix it without any issues. What do you think?

**Comment by zamitto** [comment]
@zenflow 

Antiviruses detects not signed .exe files as maliciois frequently.
The only known solution is to pay a 400$ license, what is 100% not viable.

If you have any specific question about the safety of the code, please show us and we will help you

**Comment by ArjixWasTaken** [comment]
> Windows Defender detects Trojan:Win32/Acll in the setup.exe. Any ideas why?

does it still do that if you build it yourself?

**Comment by KokaKiwi** [comment]
For information, VirusTotal scoring the installer at 14/71 is not good look either, no matter the signature thing: https://www.virustotal.com/gui/file/541a1966114e166cc5807973c227ad72fea6d687ce7c2e70293f794751247427

**Comment by hydralauncher** [comment]
@KokaKiwi I am completely aware of that, but you can image that simply pasting the VT link here is not even close to be helpful for us. It's not a bug and it's not something that I can even control, a game launcher is something that will require sole level of privilege and there's not much that I can do about it.

I'll reiterate that posting VT links won’t tell me much at all, since all the reported behaviours are expected and all the releases are built from the source using GitHub Actions.

And I don't know exactly which research you did it yourself, but some of those flags would indeed go away with code signing (specially Generic ones and NotAVirus).

**Comment by davidied** [comment]
![IMG_20240504_225811019 1](https://github.com/hydralauncher/hydra/assets/163922924/8b08cc14-f6ff-4e92-9b76-177a25c1434a)
here is an alert about trojan.

**Comment by zamitto** [comment]
@davidied as already stated, this is a false positive. We have updated our build pipeline and it seems to have resolved a lot of false positives. If you feel unsafe, wait until we release the next update

**Comment by devcoar** [comment]
> @davidied as already stated, this is a false positive. We have updated our build pipeline and it seems to have resolved a lot of false positives. If you feel unsafe, wait until we release the next update

I can confirm. The latest build does not trigger Windows Defender warning, and it did before.
