### ISSUE TITLE
[REQUEST] Adding programs to the launcher

### ISSUE THREAD

**Issue by egoor1k** [hydralauncher/hydra#724]
### Is your feature request related to a problem? Please describe.

I saw a query that has already been clearly answered. I know that you can add third-party games to the library, that is, those that are already installed on your pc. But I would like to add a separate button where you can specify the path to the .exe file or shortcut. The plus side of such a solution is that it is very convenient, and you do not have to search for the game throughout the catalog. And the second plus is that the directory contains only games, and users would like to use Hydra as the main launcher and move there all their programs (for example, programs from Adobe, or even MSI Afterburner), because on the desktop they are very disturbing. In general, any program that is on the computer, it is perfectly implemented in Steam, as it is not dangerous for other users, these programs will be locally only on your PC.

### Describe the solution you'd like

Adding to the catalog not only games, but also applications will not fix this situation. After all, there are a lot of programs, and it will be difficult for the developers themselves to implement, although downloading both games and apps from hydra I am waiting. Just it will not come out as large-scale as the implementation of adding all programs from the pc, you can add only a small part of the programs of all the programs that the user uses, only popular and well-known. So I suggest adding under the tab "Settings" tab "Add a program", for example, where the user needs to choose the path to the .exe file or shortcut (about the shortcut I'm not sure if it is possible to add a purchased game from steam, that is, its shortcut in the hydra launcher, but if possible then super, I do not know exactly). And in the library will appear game/application, with its icon and name (they will be taken from the pc, not from the catalog), and the ability to change the name of the application, inpritsnipe would be nice if the file has a strange name. I apologize, I used a translator, if something is crooked, please understand. I wish success to the launcher, I believe in it!

**Comment by ObadiahF** [comment]
Hello,
I've been working on adding this feature as you've described as this has also been asked in issue #788. I've implemented the ability to add an external game or application to your library. I've followed your requested solution and made it so that the program icon is the same as the exe selected. Now I've ran into a road block when it comes implementing the "game" page and making sure it looks good. I would love to hear if you have any insights on this matter.

For a normal game all the game data is filled out. Example:
![github2](https://github.com/user-attachments/assets/36906d79-1ec5-444b-a2fc-a2ae45d28940)

But since there might be no data on the added external program we're greeted by a bleak and bland "game" page. Example: 
![github1](https://github.com/user-attachments/assets/94ac829e-513b-43f7-b0ee-a666bd18d4d6)

Now, I can get rid of the ugly icons and default text but that doesn't change that fact that it is a barren and ugly. Do you have any thoughts on how to make it look nicer?

**Comment by thegrannychaseroperation** [comment]
Not something we plan to implement.
