### ISSUE TITLE
[BUG] i cant update hydra launcher

### ISSUE THREAD

**Issue by NaviTDost** [hydralauncher/hydra#734]
### Describe the bug

i cant update hydra launcher,i delete the old versionand download the new version but is still says "v1.2.1 exodus" on the bottom right

### Steps to Reproduce

i dont know how to describe

### Expected behavior

i expect that they will help me update to the latest version of hydra launcher

### Screenshots

![Снимок — копия](https://github.com/hydralauncher/hydra/assets/174191931/3ee2dc05-75b7-44ce-adbf-e633219f1251)

### Operating System

windows 10

### Hydra Version

v1.2.1 "exodus"

**Comment by Xxxsusx** [comment]
Go to Hydra files and completely wipe out all files (delete them) and also completely empty your trashbin. After that press Win + R, type %temp% , Delete all of the files that are there and if there are some files being used by Windows, mark the "Do the same option for all items" and press "Ignore".

After that, download the v2.0.2 .exe file and download it or you can attempt to install v2.0.2 (Portable Version) which won't have a setup included and you will already have the folder of the latest version.

(Remember that, since you're using v1.2.1, most of the settings, data and even your library will be reset since you will be fully deleting the old version of Hydra. Also remember that, all games that you have installed will not be deleted in your system but you will still have to add the games back to your library and when you're inside v2.0.2, make sure to create a Hydra Account so it saves your settings, library and make sure to adjust all the setings there as you want.)

**Comment by zamitto** [comment]
Closing issue as no response in a long time.
If this error is still happening in 2.1.7, feel free to reopen or open a fresh new issue.
