### ISSUE TITLE
Game information is not loading [BUG] 

### ISSUE THREAD

**Issue by Nifelhard** [hydralauncher/hydra#845]
### Describe the bug

Information about the game "I am Alive" is not loading. Downloaded from other sources and added to my library.

### Steps to Reproduce

1. Open the launcher
2. Find the game "I Am Alive"
3. Add to library

### Expected behavior

All information about the game will be available. Perhaps this problem is not only with the profile of this game

### Screenshots

![image](https://github.com/user-attachments/assets/8cb48791-8c32-4a1b-b608-46e6bf0ac8a8)

### Operating System

WIndows 11

### Hydra Version

2.0.3

**Comment by JackEnx** [comment]
This occurs because this game is blocked in your country, the hydra information is collected from Steam, if Steam blocks a certain game in your country the information about the game will not be loaded, the temporary solution we use is the text that inform about the block, if there is a download available you can download it without problems.
![image](https://github.com/user-attachments/assets/bdc6ce30-52e5-4c49-9ef6-7ab2833d5cf5)
