### ISSUE TITLE
Problems when downloading python dependencies

### ISSUE THREAD

**Issue by albano-a** [hydralauncher/hydra#86]
I'm following the commands in the README.md, and when I run the command `pip install -r requirements.txt` I stumble upon the error 
```
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent
```
I tried `pip install libtorrent` and got the same error... It is a problem with my Python version (3.12.2)? Or it's something else?

![WindowsTerminal_24 04 26_08 24_426p_w9UFGO](https://github.com/hydralauncher/hydra/assets/110417140/76415a14-13f3-4f42-9122-dc1716e2926a)

**Comment by Magrid0** [comment]
I got the same problem on EndeavorOS

**Comment by hydralauncher** [comment]
The README.md states that you need Python 3.9.

**Comment by Magrid0** [comment]
@hydralauncher i've just retried on a fresh installed arch vm, after downloading python 3.9 from the AUR i still get the error

`magrid@archlinux ~/D/p/hydra (main) [1]> pip install libtorrent --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent
`

**Comment by guizaodev** [comment]
Make sure you are using `python 3.9` with

```bash
python --version
```

If not, you can download Python 3.9.13 directly from [Python website](https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe).

**Comment by Magrid0** [comment]
> If you have more than one python version on your machine, you can create a virtual environment with the version of your choice
> 
> ```bash
> 
> python -X.Y -m venv my-env
> 
> ```

I'll try that

**Comment by hydralauncher** [comment]
Closing this since the OP hasn't give any feedback.
