### ISSUE TITLE
[REQUEST] Replace BitTorrent with Qbittorrent

### ISSUE THREAD

**Issue by DarkKalkor** [hydralauncher/hydra#892]
### Is your feature request related to a problem? Please describe.

This torrent is very bad because of its speed, meanwhile qbittorent works much better and the speed is better. I installed GTA 5 without setting qbittorent in 3 or 4 hours. Meanwhile, via BitTorrent it will take forever to install.

### Describe the solution you'd like

Just change BitTorrent to qbittorent

### Additional context

Nothing to write anything else, just replace BitTorrent with Qbittorent. This torrent is much better than Bittorrent

**Comment by DarkKalkor** [comment]
This torrent downloads at 8 or 10 Mbps, while BitTorrent downloads at 2 or 1. It's really awful to download games through this piece of crap torrent, please change it.

**Comment by JackEnx** [comment]
BitTorrent is a protocol https://en.wikipedia.org/wiki/BitTorrent, same name as BitTorrent software https://en.wikipedia.org/wiki/BitTorrent_(software), hydra use libtorrent, same as qBittorrent https://www.libtorrent.org/, you can see this information on the qBittorrent github page https://github.com/qbittorrent/qBittorrent, some times you have conflicts because both use same lib.

**Comment by DarkKalkor** [comment]
> BitTorrent is a protocol https://en.wikipedia.org/wiki/BitTorrent, same name as BitTorrent software https://en.wikipedia.org/wiki/BitTorrent_(software), hydra use libtorrent, same as qBittorrent https://www.libtorrent.org/, you can see this information on the qBittorrent github page https://github.com/qbittorrent/qBittorrent, some times you have conflicts because both use same lib.

Ahh I see. Thanks for the answer.
