### ISSUE TITLE
Strange Behavior in exe, possible threat?

### ISSUE THREAD

**Issue by AlexOliveiraaDev** [hydralauncher/hydra#94]
**The file "Setup.exe" appears to be classified as a STEALER, indicating that it may have functionalities related to information theft.**

**Suspicious Behaviors:**

**Defense Evasion (TA0005):**
- Obfuscated files or information (T1027) using XOR encoding.
- Registry modifications (T1112) to delete registry values.

**Discovery (TA0007):**
- Performs various registry queries (T1012).
- Discovers session username (T1033).
- Conducts file and directory discovery (T1083).
- Discovers user account information (T1087).

**Anti-Analysis:**
- References anti-VM strings to detect virtual machine environments such as Xen, VMWare, and VirtualBox.
- Also references strings of analysis tools.

Could you explain the reason behind these suspicious behaviors?

[Behavior Virus Total](https://www.virustotal.com/gui/file/541a1966114e166cc5807973c227ad72fea6d687ce7c2e70293f794751247427/behavior)

**Comment by hydralauncher** [comment]
Perhaps I'm a little bit confused about what exactly did you expect by opening this issue. How am I supposed to explain false positives? You literally have the whole code at your disposal and the pipelines explicitly generating the releases from it.

**Comment by AlexOliveiraaDev** [comment]
"My concern isn't the false positive, but rather the behavior. Why is it conducting an analysis to determine if it's running on a VM? And what's the reason for obfuscating certain files and information? I'm not accusing, just asking."

**Comment by hydralauncher** [comment]
How am I even supposed to know in-depth why the binary is flagged by an arbitrary antivirus software? There's no VM detection in the code, there's not a single form of obfuscation HENCE the project being open-source; “possible threat?” does sound a lot like an accusation over a question, that's why I see no point in this issue. If you feel like there's any shady behaviour going on, please keep it straight and technical as it should be on this platform: POINT IT IN THE CODE, DON'T SPECULATE.
